[package]
name = "tikv"
version = "0.0.1"
keywords = ["KV", "distributed-systems", "raft"]

[features]
default = []
dev = ["clippy"]

[lib]
name = "tikv"

[[bin]]
name = "tikv-server"

[[bin]]
name = "bench-tikv"
path = "benches/bin/bench-tikv.rs"

[[bin]]
name = "tikv-dump"

[[test]]
name = "tests"

[[test]]
name = "benches"
path = "benches/benches.rs"

[dependencies]
log = "0.3"
byteorder = "0.5"
rand = "0.3"
quick-error = "0.2"
tempdir = "0.3"
uuid = "0.1"
time = "0.1"
threadpool = "1.0.0"
toml = "0.1"
num = "0.1"
cadence = "0.5.0"
libc = "0.2.11"
crc = "1.2"
clippy = {version = "*", optional = true}

# The getopts in crate.io is outdated, use the latest getopts instead.
[dependencies.getopts]
git = "https://github.com/rust-lang-nursery/getopts"

[dependencies.rocksdb]
git = "https://github.com/ngaut/rust-rocksdb.git"

[dependencies.protobuf]
git = "https://github.com/stepancheg/rust-protobuf.git"

[dependencies.bytes]
git = "https://github.com/carllerche/bytes"

[dependencies.kvproto]
git = "https://github.com/pingcap/kvproto"
branch = "tiancaiamao/handshake-dispatch-conn"

[dependencies.tipb]
git = "https://github.com/pingcap/tipb.git"

[dependencies.mio]
git = "https://github.com/carllerche/mio.git"

[profile.dev]
opt-level = 0  # Controls the --opt-level the compiler builds with
debug = true   # Controls whether the compiler passes `-g`

# The release profile, used for `cargo build --release`
[profile.release]
opt-level = 3
debug = true
